### ISSUE TITLE
npm install donut

### ISSUE THREAD

**Issue by ungoldman** [donut-js/donutjs.club#18]
https://www.npmjs.com/package/donut is free. just sayin.

**Comment by paulcpederson** [comment]
could be a cli with some totally sweet ascii art:

```
Usage: donutjs [options]
Options:
  -a, --about           What is Donut JS?
  -s, --schedule        Schedule of the upcoming event
  -t, --tickets         Buy tickets
  -v, --version         Version number
  --help                Show help text
```

**Comment by paulcpederson** [comment]
or it's just a set of ascii art donuts and you get a random one each time.

**Comment by ungoldman** [comment]
BOTH

**Comment by obensource** [comment]
WUT!! YES!!

**Comment by jden** [comment]
:+1: :100: to ascii donuts as a module

**Comment by ungoldman** [comment]
Open call for donut ASCII art!

Also this might be worth reproducing in node on the command line:

https://www.a1k0n.net/2011/07/20/donut-math.html

**Comment by obensource** [comment]
@ungoldman oh. my. god. AMAZING!!

**Comment by obensource** [comment]
Totally worth it!

**Comment by ungoldman** [comment]
I found the donut-math person on github, they've got a more recent project called [asciitracing](https://github.com/a1k0n/asciitracing). @paulcpederson are you interested in trying to give 3d life to donny the donut?

**Comment by paulcpederson** [comment]
Down, but don't even know where to begin on that...

**Comment by ungoldman** [comment]
Guess we gotta learn C++

**Comment by emily-plummer** [comment]
Can you guys please do this then give a duo-talk in matching donut suits about it?

![image](https://media.giphy.com/media/ph9iJabfsVWCc/giphy.gif)

**Comment by jden** [comment]
> matching donut suits

omg yes pls 
![image](https://cloud.githubusercontent.com/assets/1106489/14152413/12e6d144-f668-11e5-827f-d0f007f7e3d0.png)

**Comment by obensource** [comment]
@ungoldman @paulcpederson @emily-plummer @jden YES! PLEASE! 💪🍩👍  👏🍩

**Comment by emily-plummer** [comment]
lol maybe I should make all the organizers/volunteers wear those so 'people can find us'

**Comment by ungoldman** [comment]
👋🍩👍
