### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donutjs.club#2]
For anyone who's interested in knowing what our budget might look like, the budgets for wafflejs and brooklynjs are all available online. 

WaffleJS
https://docs.google.com/spreadsheets/d/1D3_RS7sMBZZxJRSmrTM_3Rf0ZyTfD3ApbftW8TwZ468/edit

BrooklynJS
https://github.com/brooklynjs/brooklynjs.github.io/blob/master/budget.js

We've also started a preliminary budget here:
https://docs.google.com/spreadsheets/d/14LtHxjzOTyK2JyVIUcy3NIN324kwgp8sQKCxtJrlhMs/edit?usp=sharing

**Comment by obensource** [comment]
@emily-plummer thanks for sharing this, super helpful viz! :+1:

**Comment by matthewmcvickar** [comment]
Max and myself are handling this forthwith!
