### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donutjs.club#3]
We'll need to start looking into finding some companies to sponsor this event!

Ideally we could find 3 companies to sponsor each month's event at $500 per sponsor. WaffleJS & BrooklynJS have discounts for companies that want to sponsor consecutive months.

Sponsors receive their logo on the website, a minute of stage time, placement of swag and merch at event, and 2 free tickets for their employees to attend.

Any ideas on companies that might be willing to sponsor? I believe my company is in for at least one month.

**Comment by nikolaswise** [comment]
Would it make sense to approach our good cities competing donut makers?

Voodoo, Blue Star, Coco, Pip's Original, etc may be willing to at least provide the donuts!

**Comment by emily-plummer** [comment]
Oh smart! Right now we're thinking about going with coco! I'll reach out to them this week about the possibility of getting the donuts donated.

 I talked to Pips and they charge $1,150 for their donut-mobile to come to events + don't do any large orders :/

**Comment by nikolaswise** [comment]
bwaa waa Pips makes good donuts. 

Coco also makes good donuts though so I hope that pans out!

**Comment by visnup** [comment]
I assume you've seen our budget already, but we've been paying ~$700/month for our waffles, which comes out to ~$7/waffle (which I still find pretty damn expensive). After adjustment for no-show attendees though, it goes down to ~$5.25/ticket.

**Comment by obensource** [comment]
@nikolaswise @emily-plummer I'm friends with Nate Snell (founder/owner of Pips) and could reach out to him about it and see what he says?

**Comment by emily-plummer** [comment]
@obensource I've reached out about a month ago (I think to Nate) and they said they aren't able to do large batch orders :/

**Comment by obensource** [comment]
@emily-plummer oh yeah, that sounds about right. I think they really only do small batches to handle walk-in orders because they're not setup with enough equipment for doing large batches too. Hmm... Voodoo's donuts aren't the best in town, but they might be into the idea–especially since Donny is pink. I'm friends with friends of Tres Shannon (founder/owner/etc), might be worth reaching out?

My vote for tastiest donuts in town would probably go to Blue Star.
