### ISSUE TITLE
Create slides for before/after/in between talks.

### ISSUE THREAD

**Issue by matthewmcvickar** [donut-js/donutjs.club#38]
What to show on interstitial slides:
- beginning of event
  - schedule of talks
  - names of presenters and their Twitter handles
- before each talk
  - show next talk title/speaker/Twitter handle, website, etc.
- after each talk 
  - show who just spoke/Twitter handle, website, etc.

This should happen every month.

We need to figure out how to do this without complicating the AV situation.

**Comment by aaronpk** [comment]
Great idea! This could easily be done as "slides" in this website. Maybe at the same time someone adds the October speakers, they also include a RevealJS page with the same info we can use during the event.

As far as the a/v situation, we just need a computer to swap out at the podium during the break to show the "slides".

**Comment by matthewmcvickar** [comment]
This is finally done!

https://donutjs.club/event/1.html
https://donutjs.club/event/2.html
https://donutjs.club/event/3.html
https://donutjs.club/event/4.html
https://donutjs.club/event/5.html
