### ISSUE TITLE
Add event images to homepage

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donutjs.club#45]
add some images of the event to the homepage so that people can get a feel for what the event is like 

https://www.flickr.com/photos/142298874@N02/albums/72157665328966013

https://photos.google.com/share/AF1QipMB62cjOaYxVdzd0A8qLFUIGT1mLmodUgAVeO7_EPIetmMJI9GCyPfNsyuBoHI30w?key=QS1xdXcySklPSjUxWE1DbkJJRU9TX0NHamRhNFJn

**Comment by matthewmcvickar** [comment]
I think the embedded Twitter Moments do a great job of this, so I'll consider this closed! ☺️
