### ISSUE TITLE
add a license to this repo

### ISSUE THREAD

**Issue by aaronpk** [donut-js/donutjs.club#61]
There is currently no license on this repo, so it's unclear whether it's okay to reuse any content/code from it.

**Comment by matthewmcvickar** [comment]
BSD-3 license applied via https://github.com/donut-js/donut-js.github.io/commit/f2e1bde3fb76add5be4c01595d06a8d3197eac97!

**Comment by matthewmcvickar** [comment]
@paulcpederson @aaronpk @maxogden @emily-plummer @Folashade @jwithington @ungoldman @caterinasworld @boulosdib @billyroh @gcochard @blainesch @andrewvy 

As contributors to this website, you should have input on the license we apply to it. What's your opinion on how we should license the site? How should people be able to use it, how should they have to attribute us, etc?

[Here's the plain-English explainer for the BSD-3 license.](https://tldrlegal.com/license/bsd-3-clause-license-(revised))

**Comment by aaronpk** [comment]
👍 to BSD

**Comment by paulcpederson** [comment]
Sounds good to me. I'm probably the opposite of an expert on this, but shouldn't the copyright text at the top of the license include the name? Looks like right now it is just `Copyright (c) 2017, ` with nothing after the comma. The license requires people using it to also include the license, so would it be good to put `donut.js` in there (with a url to the site?) to spread the word?

**Comment by matthewmcvickar** [comment]
@paulcpederson Yes, I just noticed that and changed it to say “Copyright (c) 2017, Donut.js contributors.”

**Comment by jwithington** [comment]
No strong opinion. Thanks for pinging asking though! 👍

**Comment by matthewmcvickar** [comment]
With no opposition and some support, the BSD-3 license stays.
