### ISSUE TITLE
Event Planning - May 2017

### ISSUE THREAD

**Issue by modality** [donut-js/donutjs.club#62]
We decided that we're going to do the following things before, during and after May 2017's Donut.js.

- [x] Come up with script and roles before the event starts!
- [ ] *Speaker Candidates* - @modality will collate a list of people to approach (kindly, respectfully) 
- [ ] Order more donutjs stickers (circular and hexagonal)
- [x] *Order Donuts* @modality is back on donut duty
- [x] Confirm Aaron Parecki to give a short talk about IndieWeb
- [x] *Order More Nametags* @matthewmcvickar if possible before this event
- [x] *Email Blast* @colinwilliams we leave this in your capable hands
- [x] *Twitter Blast* @modality will write and post in Donut.js room, to blast out Thursday morning (May 25)
- [x] *Speaker Gifts* - @modality will pick these up, please comment with ideas if you have them
- [x] *Talks We'd Like To See* - Who can set up a Google Form for this? @matthewmcvickar? We will plug it at the event.

**Comment by colinswilliams** [comment]
I do have a post event email/survey, could amend it to fit what we view as current needs

**Comment by matthewmcvickar** [comment]
Talks you'd like to see: https://donutjs.club/talk-ideas/

**Comment by matthewmcvickar** [comment]
@colinswilliams Can you create a group in MailChimp that is us six organizers (Michael, Stefanie, Max, Folashade, and yourself) and send all of the current templates to it so we can see what they all look like?
