### ISSUE TITLE
Create permalinks for past talks

### ISSUE THREAD

**Issue by aaronpk** [donut-js/donutjs.club#67]
The "past speakers" page is getting pretty huge with all the embedded youtube videos. One suggestion would be to create permalinks for each month so that a page only embeds up to 4 videos at a time. For example:

* https://donutjs.club/past-speakers/january-2017/
* https://donutjs.club/past-speakers/february-2017/
* etc

Then the main "past speakers" page could have a list of all the months so that it actually loads quick again.

**Comment by matthewmcvickar** [comment]
This has been completed via https://github.com/donut-js/donutjs.club/commit/dd6986067e62ce61c28c9b0e146a4e8fe9bc7138.

- All embedded videos have been replaced with links.
- Years are linked internally, e.g., https://donutjs.club/past-speakers/#2018
- Months are linked internally, e.g., https://donutjs.club/past-speakers/#august-2018

**Comment by matthewmcvickar** [comment]
11-month turnaround on this. Not bad!
