### ISSUE TITLE
Name the fiscal sponsor on the website

### ISSUE THREAD

**Issue by brainwane** [donut-js/donutjs.club#68]
https://donutjs.club/sponsor/ says:

> Sponsorship of Donut.js goes through our fiscal sponsor (a registered nonprofit) and is fully tax-deductible.

Who is that nonprofit?

**Comment by brainwane** [comment]
(I say this partly out of curiosity, and partly as someone who'd be more interested in sponsoring a community-run tech event if I could trace the fiscal sponsorship, and partly as someone who found you via [Stumptown Syndicate's Twitter feed](https://twitter.com/stumpsyn) and is curious about whether I should bug them to list you on their site.)

**Comment by matthewmcvickar** [comment]
@brainwane Thanks for the note. Stay tuned for news on this front very soon!

**Comment by brainwane** [comment]
I see http://stumptownsyndicate.org/2017/12/13/donutjs/ . :)

**Comment by matthewmcvickar** [comment]
@brainwane Yes indeed, Stumptown Syndicate is our fiscal sponsor! I'll update the website soon!

**Comment by matthewmcvickar** [comment]
The sponsorship page has been fully overhauled! https://donutjs.club/sponsor/
