### ISSUE TITLE
November Videos!

### ISSUE THREAD

**Issue by aaronpk** [donut-js/donutjs.club#69]
* [How to Make a Donut - Cory Reed and Chris Dieringer](https://www.youtube.com/watch?v=gJwTi14n6jw)
* [Data, Design, and D3 - Kim Niedermaier](https://www.youtube.com/watch?v=Pw-8GN6eO_E)
* [Functional Programming - Kyle Shevlin](https://www.youtube.com/watch?v=-4QNj7TJjgo)

**Comment by matthewmcvickar** [comment]
Updated!

**Comment by aaronpk** [comment]
Here's the last one! https://www.youtube.com/edit?o=U&video_id=muvPFO5TsRk
