### ISSUE TITLE
Call for Performers

### ISSUE THREAD

**Issue by emily-plummer** [donut-js/donutjs.club#7]
We're looking for people to perform at our meetup!

**How do I submit a performance?**
Comment on this thread!

**What kind of performance are you looking for?**
It can be karaoke, plate-spinning, or fire-eating. Basically anything you want. If you're into, we're into it.

**How long should my performance be?**
It should be <6 min long!

**Do I need to be a good singer?**
Nope. You just need to be enthusiastic!

**What should be in my submission?**
A description of what you'll be performing and what kind of equipment you'll need.

**Comment by visnup** [comment]
Would love to duet A Whole New Workd with someone. Or A Part Of Your World. Or really, anything Disney v

**Comment by obensource** [comment]
I'd love to give an exciting, well organized music performance involving @maxogden, and a remote performer (maybe Substack, Myles Borins @thealphanerd, or my friend Eric from Blitzen Trapper). I'm able to provide the equipment needed, I'd just need to know ahead of time what kind of sound set-up we're working with (if any).

If all else, I'm also available to do a super karaoke performance of Journey's [Worlds Apart](https://www.youtube.com/watch?v=LatorN4P9aA) ;)

**Comment by TheAlphaNerd** [comment]
o/

**Comment by RuthieB** [comment]
@visnup I'll duet with you! I have some experience with that song....

**Comment by maxogden** [comment]
i would like to see @jchris rap

**Comment by jchris** [comment]
Bacon lettuce avocado and tomato 
 You don't need servers when you BLAT your data 
 With this JavaScript code in your browser 
 Users get rowdy, your app gets louder

**Comment by maxogden** [comment]
Pizza muffin taco donkey
Three are foods ones a donkey
JavaScript code really is the best
JChris raps above the rest

**Comment by paulcpederson** [comment]
having observed @obensource performing worlds apart before, I am going to go ahead and list that as a hard requirement.
